# -*- coding: utf-8 -*-
# Generated by Django 1.11.10 on 2019-03-02 08:22
from __future__ import unicode_literals

from django.db import migrations, models
import news.fields


class Migration(migrations.Migration):

    initial = True

    dependencies = [
    ]

    operations = [
        migrations.CreateModel(
            name='News',
            fields=[
                ('id', models.AutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('image', news.fields.ThumbnailImageField(null=True, upload_to='news/%Y/%m')),
                ('title', models.CharField(blank=True, max_length=50, null=True, verbose_name='제목')),
                ('content', models.TextField(blank=True, max_length=100, null=True, verbose_name='내용')),
                ('url', models.URLField(unique=True, verbose_name='url')),
                ('create_date', models.DateTimeField(auto_now_add=True, verbose_name='작성일')),
            ],
            options={
                'verbose_name': '새소식',
                'verbose_name_plural': '소식',
                'ordering': ('create_date',),
            },
        ),
    ]
