# -*- coding: utf-8 -*-
# Generated by Django 1.11.10 on 2019-03-02 08:22
from __future__ import unicode_literals

from django.db import migrations, models
import django.utils.timezone


class Migration(migrations.Migration):

    initial = True

    dependencies = [
    ]

    operations = [
        migrations.CreateModel(
            name='Post',
            fields=[
                ('id', models.AutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('title', models.CharField(max_length=200)),
                ('text', models.TextField()),
                ('created_date', models.DateTimeField(default=django.utils.timezone.now)),
                ('rating', models.CharField(max_length=30, null=True)),
                ('product', models.CharField(max_length=30, null=True)),
            ],
            options={
                'verbose_name': '자랑',
                'ordering': ['-created_date'],
            },
        ),
    ]
